
CREATE TABLE USERS(
USER_ID VARCHAR(10) NOT NULL PRIMARY KEY, 
USER_NAME VARCHAR(20) NOT NULL, 
USER_EMAIL VARCHAR(20) NOT NULL);


CREATE TABLE PRODUCT(
PRODUCT_ID VARCHAR(10) NOT NULL PRIMARY KEY,
PRODUCT_NAME VARCHAR(20) NOT NULL, 
PRODUCT_DESC VARCHAR(20) NOT NULL,
PRODUCT_PRICE INT NOT NULL);


CREATE TABLE CART(
CART_ID VARCHAR(10) NOT NULL PRIMARY KEY, 
USER_ID VARCHAR(10) NOT NULL FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
TOTAL_COST INT NOT NULL);


CREATE TABLE CARTIT(
CARTITEM_ID VARCHAR(10) NOT NULL PRIMARY KEY,
CART_ID VARCHAR(10) NOT NULL FOREIGN KEY (CART_ID) REFERENCES CART(CART_ID),
PRODUCT_ID VARCHAR(10) NOT NULL FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
QUANTITY INT NOT NULL,
SUBTOTAL INT NOT NULL);